var c = 0

click.onclick = function () {

    if (c == 0) {
        
        hiddendiv.style.display = "none"
        sidebar.style.width = "5%"
        hrhid.style.display = "none"
        vid.style.width = "90%"
        vid.style.marginLeft = "5%"
        c = 1
    }
    else {
        hrhid.style.display = "block"
        hiddendiv.style.display = "block"
        vid.style.width = "85%"
        vid.style.marginLeft = "20%"
        sidebar.style.width = "15%"
        sidebar.style.fontSize = "16px"
        c = 0
    }

}

btn0.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}

btn1.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}

btn2.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn3.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn4.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn5.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn6.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"

}
btn7.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn8.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn9.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn10.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn8.style.backgroundColor = "#eceaea"
    btn8.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn11.style.backgroundColor = "#eceaea"
    btn11.style.color = "black"
}
btn11.onclick = function () {
    this.style.backgroundColor = "black"
    this.style.color = "white"

    btn0.style.backgroundColor = "#eceaea"
    btn0.style.color = "black"
    btn1.style.backgroundColor = "#eceaea"
    btn1.style.color = "black"
    btn2.style.backgroundColor = "#eceaea"
    btn2.style.color = "black"
    btn3.style.backgroundColor = "#eceaea"
    btn3.style.color = "black"
    btn4.style.backgroundColor = "#eceaea"
    btn4.style.color = "black"
    btn5.style.backgroundColor = "#eceaea"
    btn5.style.color = "black"
    btn6.style.backgroundColor = "#eceaea"
    btn6.style.color = "black"
    btn7.style.backgroundColor = "#eceaea"
    btn7.style.color = "black"
    btn9.style.backgroundColor = "#eceaea"
    btn9.style.color = "black"
    btn10.style.backgroundColor = "#eceaea"
    btn10.style.color = "black"
}

